JWT_TOKEN_TTL_SECONDS = 86400
JWT_ALGORITHM = "HS256"

RATE_LIMIT_MAX_MESSAGES = 50
RATE_LIMIT_WINDOW_SECONDS = 3600

MAX_MESSAGE_LENGTH = 2000

CHUNK_SIZE = 500
CHUNK_OVERLAP = 50

DB_POOL_SIZE = 5
DB_MAX_OVERFLOW = 10

WORKER_MAX_RETRIES = 3
WORKER_RETRY_DELAYS = [1, 2, 4]
WORKER_STREAM_NAME = "tailoring-jobs"
WORKER_CONSUMER_GROUP = "tailoring-workers"

DOC_EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
SEMANTIC_MATCH_MODEL = DOC_EMBEDDING_MODEL
